added palindrom pattern
gautam32/Patterns pull request #18
Opened 2021-10-31 12:13 UTC by Kevinjadia

@gautam32 I've sent PR, Kindly check it

2021-10-31 12:24 UTC, gautam32 requested changes
The input for the number of rows says 6 but the code is printing only 5. Please, fix the logical error

2021-10-31 12:41 UTC, Kevinjadia commented
@gautam32 I've done the required changes

2021-10-31 17:06 UTC, Kevinjadia commented
@gautam32  Can you please check the changes I made and accept my PR ASAP?

2021-11-21 20:50 UTC, gautam32 approved these changes

2021-11-21 20:50 UTC, merged